jobs:
  upload_dev:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "scripts/package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: cd scripts && npm install --ignore-engines

      - save_cache:
          paths:
            - scripts/node_modules
          key: v1-dependencies-{{ checksum "scripts/package-lock.json" }}

      - run: cd scripts && npm run upload-dev

workflows:
  version: 2
  build:
    jobs:
      - upload_dev:
          filters:
            branches:
              only:
                - master
